const tennis = require('./tennis')
const { getGameResult, hasScoreCorrectFormat } = tennis

test('getGameResult()', () => {
    expect(() => getGameResult(1214, true)).toThrow()
    expect(getGameResult('0-0', true)).toBe('15-0')
    expect(getGameResult('0-0', false)).toBe('0-15')
    expect(getGameResult('15-0', true)).toBe('30-0')
    expect(getGameResult('30-0', true)).toBe('40-0')
    expect(getGameResult('40-0', true)).toBe('Game Player1')
    expect(getGameResult('0-40', false)).toBe('Game Player2')
    expect(getGameResult('0-40', true)).toBe('15-40')
    expect(getGameResult('40-30', false)).toBe('40-40')
    expect(getGameResult('30-40', true)).toBe('40-40')
    expect(getGameResult('40-40', true)).toBe('A-40')
    expect(getGameResult('40-40', false)).toBe('40-A')
    expect(getGameResult('A-40', true)).toBe('Game Player1')
    expect(getGameResult('40-A', false)).toBe('Game Player2')
    expect(getGameResult('A-40', false)).toBe('40-40')
    expect(getGameResult('40-A', true)).toBe('40-40')
})

test('hasScoreCorrectFormat()', () => {
    expect(hasScoreCorrectFormat('12313')).toBe(false)
    expect(hasScoreCorrectFormat(12)).toBe(false)
    expect(hasScoreCorrectFormat('sdf')).toBe(false)
    expect(hasScoreCorrectFormat(null)).toBe(false)
    expect(hasScoreCorrectFormat('0-0')).toBe(true)
    expect(hasScoreCorrectFormat('15-0')).toBe(true)
    expect(hasScoreCorrectFormat('10-0')).toBe(false)
    expect(hasScoreCorrectFormat('30-30')).toBe(true)
    expect(hasScoreCorrectFormat('40-40')).toBe(true)
    expect(hasScoreCorrectFormat('40-A')).toBe(true)
    expect(hasScoreCorrectFormat('A-40')).toBe(true)
    expect(hasScoreCorrectFormat('A-A')).toBe(false)
    expect(hasScoreCorrectFormat('15-A')).toBe(false)
})